#!/usr/bin/env python3
"""
Check translation coverage across all languages.
Reports missing files and aims for consistency.

Usage:
    python3 scripts/check_translations.py docs/reference docs/std
"""

import os
import sys
import re
import glob
from collections import defaultdict

LANGUAGES = ['en', 'de', 'es', 'it', 'pt', 'ru', 'zh-cn', 'zh-tw']
LANG_NAMES = {
    'en': 'English', 'de': 'German', 'es': 'Spanish', 'it': 'Italian',
    'pt': 'Portuguese', 'ru': 'Russian', 'zh-cn': 'Chinese (Simplified)',
    'zh-tw': 'Chinese (Traditional)',
}

def get_lang(filename):
    """Extract language suffix from a filename."""
    base = os.path.basename(filename)
    for lang in LANGUAGES:
        if lang == 'en':
            # English files have no language suffix
            if not re.search(r'\.(de|es|it|pt|ru|zh-cn|zh-tw)\.', base):
                return 'en'
        else:
            if f'.{lang}.' in base:
                return lang
    return None

def analyze_directory(dirpath):
    """Analyze a directory of translated documentation."""
    files = glob.glob(os.path.join(dirpath, '*.md'))
    
    # Group by base name
    groups = defaultdict(dict)
    for f in files:
        base = os.path.basename(f)
        lang = get_lang(base)
        if lang:
            # Get the base name without language suffix
            if lang == 'en':
                stem = base
            else:
                stem = base.replace(f'.{lang}.md', '.md')
            groups[stem][lang] = f
    
    return groups

def report_directory(dirpath, name):
    """Report translation status for a directory."""
    groups = analyze_directory(dirpath)
    
    total = len(groups)
    complete = 0
    missing_any = 0
    
    for stem, langs in sorted(groups.items()):
        missing = [l for l in LANGUAGES if l not in langs]
        if not missing:
            complete += 1
        else:
            missing_any += 1
            if len(missing) <= 3:  # Only report if few missing
                pass  # Report below
    
    print(f"\n## {name} ({total} documents)")
    print(f"| Status | Count |")
    print(f"|--------|-------|")
    print(f"| Fully translated | {complete} |")
    print(f"| Missing translations | {missing_any} |")
    print()
    
    # Report specific gaps
    for stem, langs in sorted(groups.items()):
        missing = [l for l in LANGUAGES if l not in langs]
        if missing:
            english_file = langs.get('en', stem)
            print(f"❌ **{stem}**: missing {', '.join(LANG_NAMES[l] for l in missing)}")
    
    # Report files that exist but weren't in the original English set
    en_files = {stem for stem, langs in groups.items() if 'en' in langs}
    non_en_only = {stem for stem, langs in groups.items() if 'en' not in langs}
    if non_en_only:
        for stem in sorted(non_en_only):
            langs_present = ', '.join(LANG_NAMES[l] for l in groups[stem])
            print(f"⚠️  **{stem}**: exists in {langs_present} but NOT in English")

def main():
    dirs = sys.argv[1:] if len(sys.argv) > 1 else []
    if not dirs:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        docs_dir = os.path.join(script_dir, '..')
        dirs = [
            os.path.join(docs_dir, 'reference'),
            os.path.join(docs_dir, 'std'),
        ]
    
    print("# Translation Coverage Report\n")
    overall_complete = 0
    overall_total = 0
    
    for d in dirs:
        if os.path.isdir(d):
            name = os.path.basename(d)
            report_directory(d, name)
    
    print("\n---\n*Report generated by scripts/check_translations.py*")

if __name__ == "__main__":
    main()
